name: noor_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0 # for simple animations
  animated_text_kit: ^4.2.3 # animations for the text
  carousel_slider: ^5.0.0   # carousel slider :)
  cupertino_icons: ^1.0.8  
  firebase_auth: ^5.5.4 
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.2
  get: ^4.7.2
  glowy_borders: ^1.0.2   # to make Animated Gradient Border
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1 # smooth page indicator :)
  hidable: ^1.0.6               # to hide the widget when scrolling
  curved_navigation_bar: ^1.0.6 # custom bottom navigation bar
  flutter_advanced_drawer: ^1.5.0 # custom drawer
  page_flip: ^0.2.5+1 # to make a page flip animation
  # youtube_player_flutter: ^8.1.1
  webview_flutter: ^4.0.7 
  badges: ^2.0.2
  readmore: ^2.2.0
  animated_button: ^0.3.1
  get_storage:
  flutter_credit_card: ^4.1.0
  photo_view: ^0.15.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2 # to take the current location for the user 
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  geocoding: ^4.0.0 # to take the names for the streets from the map



  
  # wave_blob: ^1.0.5 # wave blob
  # flutter_credit_card: ^4.1.0 # to make a 3D credit card 
  # motion: ^2.0.1  # to add motion to your widget (for desktop)
  anim_search_bar: ^2.0.3 # custom search bar
  input_history_text_field: ^0.4.0 # to make a history to your text field
  hotspot: ^0.1.3 # to make a tour in the app
  animations: ^2.0.11 # to make animations most important (Container transform)
  local_hero_transform: ^1.0.5 #  creating seamless hero transitions between grid and list views
  scroll_highlight_text: ^1.0.0 # to let you high light any text you search for
  draggable_home: ^1.0.5 # draggable home
  redacted: ^1.0.13 # to make a shimmer effect
  like_button: ^2.1.0 # to make a simple like effect
  flutter_staggered_grid_view: ^0.7.0 # custom grid view
  
  # فواتير
  # ideia* to make it like gample :)
  # if the user press on the price, become lower 
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/animations/loading_blue.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
