name: noor_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  animated_text_kit: ^4.2.3
  animate_do: ^4.2.0
  carousel_slider: ^5.0.0
  glowy_borders: ^1.0.2
  flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
